# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode8

before_install:
- gem update cocoapods --pre --no-ri --no-rdoc
- pod repo update

script:
- set -o pipefail && xcodebuild test -workspace Example/DeluxeInjection.xcworkspace -scheme DeluxeInjection-Example -destination 'platform=iOS Simulator,name=iPhone 6' ONLY_ACTIVE_ARCH=YES | xcpretty
- pod lib lint --verbose

after_success:
  - bash <(curl -s https://codecov.io/bash)
