# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode8
podfile: Example/Podfile
cache: cocoapods

before_install:
- gem install slather --no-ri --no-rdoc
- gem update cocoapods --no-ri --no-rdoc
- pod install --repo-update --project-directory=Example

script:
- set -o pipefail && xcodebuild test -workspace Example/DeluxeInjection.xcworkspace -scheme DeluxeInjection-Example -destination 'platform=iOS Simulator,name=iPhone 6' ONLY_ACTIVE_ARCH=YES | xcpretty
- pod lib lint --verbose

after_success:
- slather
